### ISSUE TITLE
Mouse movement does not work smoothly

### ISSUE THREAD

**Issue by kanlukasz** [schorschii/RemotePointer-Android#4]
Hi

I found your app, it looks great and meets my requirements.
I'd like to buy keyboard pro function, but one thing is not working properly for me.

Mouse movement on the computer screen is not smooth, the mouse jumps more or less, is laggy and choppy, etc.
What do you think could be the reason for this? Is there anything I can do about it?
My internet connection is perfect. I tested it on two laptops

My OS: Windows 11
My Phone: Motorola G84 (Android 14)
App version: 2.3.5
Server version: 2.3

**Comment by schorschii** [comment]
Does the laser pointer lags the same like as the mouse?

**Comment by kanlukasz** [comment]
Yes

**Comment by schorschii** [comment]
Then there is nothing I can do about it. The latency in your internal network (WiFi) is too high. It has nothing to do with your internet connection. You can try connecting the notebooks via LAN cable instead of WiFi or replacing your router.
